### ISSUE TITLE
default config is not working

### ISSUE THREAD

**Issue by Shedarshian** [hexojs/hexo-math#104]
I installed and used the default config, but the mathjax was not rendering anything.
When I add `extensions: ["tex2jax.js"], jax: ["input/TeX", "output/HTML-CSS"]` to config just as the mathjax 2.0 documentation's example, it works.
the _config.yml looks like this
```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js
    config:
      # MathJax config
      tex2jax:
        inlineMath: [ ['$','$'], ["\\(","\\)"] ]
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        processEscapes: true
      TeX:
        equationNumbers:
          autoNumber: "AMS"
      extensions: ["tex2jax.js"]
      jax: ["input/TeX", "output/HTML-CSS"]
```
