### ISSUE TITLE
default config not working while serve at local works

### ISSUE THREAD

**Issue by Lonenso** [hexojs/hexo-math#120]
I simply run ```npm install hexo-math --save```. And It works fine at local (```hexo s```). But after ```hexo clean && hexo d```, mathjax's cdn source's scheme is http. so error occurs. 
what should i do? And what should i provide?
> Mixed Content: The page at 'https://lonenso.github.io/2020/05/20/leetcode-1453/' was loaded over HTTPS, but requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'. This request has been blocked; the content must be served over HTTPS

```hexo clean && hexo g``` , scheme is http. Then ```hexo s```, dev tools says scheme is https. 
![Snipaste_2020-05-20_18-54-56](https://user-images.githubusercontent.com/22173979/82438321-6e6e9180-9acb-11ea-9f49-a0cd060f71ee.jpg)
![Snipaste_2020-05-20_18-55-31](https://user-images.githubusercontent.com/22173979/82438362-81816180-9acb-11ea-9311-7b83baafb0ec.jpg)

**Comment by YoshinoriN** [comment]
@Lonenso 
I assume your `_config.yaml` is wrong.
Please check `math -> mathjax -> src`.

```yaml
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML
    config:
```
