### ISSUE TITLE
公式居中突出显示

### ISSUE THREAD

**Issue by XieRuicheng** [hexojs/hexo-math#138]
使用 `{% mathjax %} ... {% endmathjax %}` 包裹的公式是 inline 形式的，如何才能突出显示？

目前我的文本是：
``` MARKDOWN
Solving the integral

{% mathjax %}
\int_{0}^{+\infty}\frac{\sin x}{x}dx,
{% endmathjax %}
```
![image](https://user-images.githubusercontent.com/20857887/102159186-03990380-3ebe-11eb-8932-96a7ef7bad26.png)

想让公式居中显示并编号，请要怎么做？

---
我的配置文件是

``` YAML
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    options:
      conversion:
        display: True
      tex:
      svg:
  katex:
    css: custom_css_source
    js: custom_js_source # not used
    config:
      # KaTeX config
```
