### ISSUE TITLE
Centering Forumlas

### ISSUE THREAD

**Issue by Machine-Hum** [hexojs/hexo-math#177]
How do you center formulas or change properties like padding from CSS? Are there any examples?

**Comment by lorezyra** [comment]
If you look at the rendered HTML, you should see `<span class="katex"><!-- MathML code --></span>`... If you know how to write CSS, then it should be obvious.

I created the following for my use-case:
```SCSS
span.katex,
math {
  color: var(--textColor);
  padding: 1rem 0;
  margin: 0.5rem;
  line-height: 2rem;
}
```

It would be trivial to add `display` and alignment rules to that block.
