### ISSUE TITLE
How to config it to make it work?

### ISSUE THREAD

**Issue by ChenZhongPu** [hexojs/hexo-math#26]
After installing it, I just add the followings to `_config.xml`

```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: custom_mathjax_source
    config:
      # MathJax config
  katex:
    css: custom_css_source
    js: custom_js_source # not used
    config:
      # KaTeX config
```

When I run it:

```
 ~/Project/gitwork/blogGitPage  hexo s
INFO  [hexo-math] Using engine 'mathjax'
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
```

However, the `Simple inline $a = b + c$.` is not displayed in math format.

Do I config it correctly?

**Comment by akfish** [comment]
Normally you don't need to add anything in your `_config.yml`. It works by default.
If you do need a different MathJax script source other than its official CDN, you should provide a valid `math.mathjax.src` value. Your current configuration is `custom_mathjax_source`, which is not valid.

Remove all your configuration will fix your problem.

**Comment by ChenZhongPu** [comment]
Now I have removed the configuration, but it still does not work.  Do I need to do other else work after `npm install hexo-math --save`?  By the way, the version of hexo is `3.1.1`.

**Comment by akfish** [comment]
What's the generated HTML looks like?

**Comment by akfish** [comment]
And also your site's `package.json`?

**Comment by ChenZhongPu** [comment]
The `package.json`:

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.1",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.3",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.1.2",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-jade": "^0.1.0",
    "hexo-renderer-marked": "^0.2.6",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-sass": "^0.2.0",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-server": "^0.1.2"
  }
}
```
Do I need add 

```
plugins:
 - hexo-math
```
in `_config.xml` ?

**Comment by akfish** [comment]
Try run `hexo clean` first see if that will fix it.

**Comment by ChenZhongPu** [comment]
It still does not works.

**Comment by akfish** [comment]
What's the generated HTML looks like?

**Comment by ChenZhongPu** [comment]
You can view its source at : http://chenzhongpu.github.io/2016/04/05/assert%E6%98%AF%E4%B8%AA%E5%AE%8F/

<img width="136" alt="screen shot 2016-04-07 at 11 20 25 am" src="https://cloud.githubusercontent.com/assets/2310958/14339642/c403f9f2-fcb2-11e5-9823-80f22fe80dae.png">

**Comment by ChenZhongPu** [comment]
Currently, the `_config.xml`

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 陈中普
subtitle: Zhongpu Chen's Blog
description:
author: Zhongpu Chen
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chenzhongpu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [README.md, 404.html, about/time.html]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: maupassant


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/ChenZhongPu/ChenZhongPu.github.io.git
  branch: master
```

**Comment by akfish** [comment]
It seems to be a compatibility issue between `hexo-inject` and `hexo-renderer-jade`. I'll look into it further once I'm free.

**Comment by zqchen90** [comment]
With the same problem

**Comment by ziyuang** [comment]
Can I switch to other renderers if `hexo-renderer-jade` is the culprit?

**Comment by akfish** [comment]
@ziyuang Sure. `hexo-inject` is tested with built-in swig renderer and `hexo-renderer-ejs`. But you are stuck with your theme developer's choice.

**Comment by ziyuang** [comment]
@akfish I am using the default landscape theme. It looks to me that it uses EJS not Jade since all files under `themes/landscape/layout` are with extension `.ejs`.

**Comment by ziyuang** [comment]
OK, if I clear the whole `math:` part in `_config.yml`, the inline math will be fine (and now it uses MathJax). Now how can I add the delimiter of display math (`displayMath: [ ['$$','$$'], ['\[','\]'] ]`) if I am not allowed to configure it in `_config.yml`? The current configuration generated in the HTML file is

```
MathJax.Hub.Config({
    "tex2jax":{
        "inlineMath":[["$","$"],["\\(","\\)"]],
        "skipTags":["script","noscript","style","textarea","pre","code"],
        "processEscapes":true},
    "TeX":{
        "equationNumbers":{
            "autoNumber":"AMS"}}});
```

**Comment by akfish** [comment]
@ziyuang You will have to escape special characters with`$...$` and `$$...$$` syntax depending on the Markdown renderer you are using, They are not processed by math-jax. The rendering of those syntax is provided by MathJax, which runs in browser.
`{% math %}...{% endmath %}` will not have those issues.

**Comment by fusion809** [comment]
This plugin repeatedly failed for me, no matter what I did to `_config.yml` or how I inserted math into documents or whether I ran `hexo clean` first before starting the server and generating. This is why I am here to recommend if anyone is still finding this plugin fails for them to use the [`hexo-renderer-mathjax`](https://github.com/phoenixcw/hexo-renderer-mathjax) plugin instead as for me it worked as soon as I ran `npm install hexo-renderer-mathjax --save` from my Hexo site's root folder.

**Comment by pcwerk** [comment]
@fusion809 looks good 

```
npm install hexo-renderer-mathjax --save
```

Appears to work.  Thanks!

**Comment by Haojen** [comment]
i have this problem too

**Comment by D0048** [comment]
Encountering the same here.

**Comment by godshen** [comment]
this problem bothered me few days, who can help me

**Comment by CntChen** [comment]
the following config in `_config.yml` works for me:
```yml
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      # MathJax config
  katex:
    css: #custom_css_source
    js: #custom_js_source # not used
    config:
      # KaTeX config
```
set `math.mathjax.src` as `//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML` as mentioned in [README.md](https://github.com/hexojs/hexo-math/blob/3.0.4/README.md#config)

**Comment by lonelyWaiting** [comment]
i have this problem too.but now it works.
After installing the plug-in I did not find the hexo-math folder.
then i install [hexo-renderer-mathjax](https://github.com/phoenixcw/hexo-renderer-mathjax)
now i found `hexo-math` folder under `node_modules` directory
But still can not work.
open  `node_models\hexo-math\lib\option.js`
``` js
var DEFAULT_OPTS = exports.DEFAULT_OPTS = {
  engine: 'mathjax',
  mathjax: {
    src: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js",
    config: {
      tex2jax: {
        inlineMath: [['$', '$'], ["\\(", "\\)"]],
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
        processEscapes: true
      },
      TeX: {
        equationNumbers: {
          autoNumber: "AMS"
        }
      }
    }
  },
  katex: {
    css: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css",
    js: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js",
    config: {
      throwOnError: false,
      errorColor: "#cc0000"
    }
  }
};
```
modify `mathjax/src'
``` js
var DEFAULT_OPTS = exports.DEFAULT_OPTS = {
  engine: 'mathjax',
  mathjax: {
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML",
    config: {
      tex2jax: {
        inlineMath: [['$', '$'], ["\\(", "\\)"]],
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
        processEscapes: true
      },
      TeX: {
        equationNumbers: {
          autoNumber: "AMS"
        }
      }
    }
  },
  katex: {
    css: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css",
    js: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js",
    config: {
      throwOnError: false,
      errorColor: "#cc0000"
    }
  }
};
```
now it works.

**Comment by NoahDragon** [comment]
Close as many solutions have provided.

**Comment by XieRuicheng** [comment]
This plugin can work in the theme *NexT*, but **cannot** work in any other themes. No matter what I do in `_config.yml` or change the markdowm enging. Thinks @fusion809 I use plugin `hexo-renderer-mathjax` and fixed it.

**Comment by XieRuicheng** [comment]
This plugin can work in the theme *NexT*, but **cannot** work in any other themes. No matter what I do in _config.yml or change the markdowm enging. Thinks to @fusion809 I add the plugin `hexo-renderer-mathjax` and @lonelyWaiting I change the cdn fixed it.
Here is the ditails:
1. Install hexo-renderer-mathjax
```
npm install hexo-renderer-mathjax --save
```
2. Add  to `_config.yml`
```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      # MathJax config
  katex:
    css: #custom_css_source
    js: #custom_js_source # not used
    config:
      # KaTeX config
 ```
Then, it will work.
- - -
**Notice**: **DONOT** uninstall `hexo-math`.
