### ISSUE TITLE
why I have to  install twice to make it work?

### ISSUE THREAD

**Issue by nomemo** [hexojs/hexo-math#52]
![2018-04-07 4 48 58](https://user-images.githubusercontent.com/2560789/38444207-04b691d2-3a21-11e8-8c60-b735affbd39c.png)

## install details

after I install the first time

I run the `hexo s`, but nothing happend.

then I add some config to `_config.yml` as doc says:

```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      # MathJax config
  katex:
    css: #custom_css_source
    js: #custom_js_source # not used
    config:
      # KaTeX config
```
and I run the `hexo s` again, not work.

at last, I install again.

It seems to work fine.

why?
